#!/usr/bin/env python

import logging

import virt.driver.vbox as vbox

import virt.log
import virt.config
import virt.arguments


def main():
    args = virt.arguments.define_arguments(
        vbox.driver_info(),
        vbox.list,
        vbox.create,
        vbox.destroy,
        vbox.start,
        vbox.stop
    ).parse_args()


    log_level = logging.WARN
    if (args.verbose == 1): log_level = logging.INFO
    if (args.verbose >  1): log_level = logging.DEBUG
    logger = virt.log.init_logger(log_level)

    vbox.driver_test(logger)

    args.func(args, virt.config.get_config(), logger)

if (__name__ == "__main__"):
    main()
